-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-09-26 06:26:41 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--DISHI JAIN
--30759307

SET ECHO ON
SPOOL tds_schema_output.txt;


DROP TABLE accommodate CASCADE CONSTRAINTS;

DROP TABLE cancel_duration CASCADE CONSTRAINTS;

DROP TABLE cancellation CASCADE CONSTRAINTS;

DROP TABLE demerit CASCADE CONSTRAINTS;

DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE engine CASCADE CONSTRAINTS;

DROP TABLE licence_type CASCADE CONSTRAINTS;

DROP TABLE manf_country CASCADE CONSTRAINTS;

DROP TABLE manufacturer CASCADE CONSTRAINTS;

DROP TABLE model CASCADE CONSTRAINTS;

DROP TABLE offence CASCADE CONSTRAINTS;

DROP TABLE police_allocation CASCADE CONSTRAINTS;

DROP TABLE police_officer CASCADE CONSTRAINTS;

DROP TABLE police_station CASCADE CONSTRAINTS;

DROP TABLE registration CASCADE CONSTRAINTS;

DROP TABLE suspension CASCADE CONSTRAINTS;

DROP TABLE suspension_date CASCADE CONSTRAINTS;

DROP TABLE vehice CASCADE CONSTRAINTS;

DROP TABLE vehicle_type CASCADE CONSTRAINTS;

CREATE TABLE accommodate (
    model_name   VARCHAR2(50 CHAR) NOT NULL,
    eng_typ      VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN accommodate.model_name IS
    'Model Name of the model';

COMMENT ON COLUMN accommodate.eng_typ IS
    'Type of engine. Can be more than one value.';

ALTER TABLE accommodate ADD CONSTRAINT accomodate_pk PRIMARY KEY ( model_name,
                                                                   eng_typ );

CREATE TABLE cancel_duration (
    cancel_reason          VARCHAR2(20 CHAR) NOT NULL,
    cancel_duration_time   NUMBER NOT NULL
);

COMMENT ON COLUMN cancel_duration.cancel_reason IS
    'The reason of cancellation';

COMMENT ON COLUMN cancel_duration.cancel_duration_time IS
    'The duration in months causing cancellation';

ALTER TABLE cancel_duration ADD CONSTRAINT cancel_duration_pk PRIMARY KEY ( cancel_reason );

CREATE TABLE cancellation (
    cancel_id                   NUMBER NOT NULL,
    cancel_date                 DATE NOT NULL,
    cancel_court_date           DATE,
    cancel_licence_renew_date   DATE,
    cancel_reason               VARCHAR2(20 CHAR) NOT NULL,
    driver_licence_no           NUMBER NOT NULL
);

COMMENT ON COLUMN cancellation.cancel_id IS
    'Surrogate key. Cancellation id';

COMMENT ON COLUMN cancellation.cancel_date IS
    'Date on which licence is cancelled';

COMMENT ON COLUMN cancellation.cancel_court_date IS
    'Date of hearing in court after licence is cancelled';

COMMENT ON COLUMN cancellation.cancel_licence_renew_date IS
    'Licence renew date after court hearing';

COMMENT ON COLUMN cancellation.cancel_reason IS
    'The reason of cancellation';

COMMENT ON COLUMN cancellation.driver_licence_no IS
    'licence number';

ALTER TABLE cancellation ADD CONSTRAINT cancellation_pk PRIMARY KEY ( cancel_id );

ALTER TABLE cancellation ADD CONSTRAINT key_2 UNIQUE ( cancel_date );

CREATE TABLE demerit (
    demerit_code                    VARCHAR2(10 CHAR) NOT NULL,
    demerit_desc                    VARCHAR2(10 CHAR) NOT NULL,
    demerit_point                   NUMBER NOT NULL,
    demerit_causing_cancellation    VARCHAR2(4 CHAR) NOT NULL,
    demerit_cancellation_duration   NUMBER NOT NULL
);

COMMENT ON COLUMN demerit.demerit_code IS
    'Code of the demerit';

COMMENT ON COLUMN demerit.demerit_desc IS
    'Demerit Description';

COMMENT ON COLUMN demerit.demerit_point IS
    'Demerit points for a particular demerit';

COMMENT ON COLUMN demerit.demerit_causing_cancellation IS
    'Demerit Causing Cancellation. Yes or No';

COMMENT ON COLUMN demerit.demerit_cancellation_duration IS
    'Duration in months of licence cancellation';

ALTER TABLE demerit ADD CONSTRAINT demerit_pk PRIMARY KEY ( demerit_code );

CREATE TABLE driver (
    driver_licence_no            NUMBER NOT NULL,
    driver_licence_status        VARCHAR2(20 CHAR) NOT NULL,
    driver_fname                 VARCHAR2(20 CHAR) NOT NULL,
    driver_lname                 VARCHAR2(20 CHAR) NOT NULL,
    driver_street                VARCHAR2(10 CHAR) NOT NULL,
    driver_town                  VARCHAR2(10 CHAR) NOT NULL,
    driver_postcode              NUMBER NOT NULL,
    driver_dob                   VARCHAR2(15 CHAR) NOT NULL,
    driver_licence_expiry_date   DATE NOT NULL,
    driver_demerit_point         NUMBER NOT NULL
);

COMMENT ON COLUMN driver.driver_licence_no IS
    'The licence number of the driver';

COMMENT ON COLUMN driver.driver_licence_status IS
    'The licence status of the driver';

COMMENT ON COLUMN driver.driver_fname IS
    'The driver first name';

COMMENT ON COLUMN driver.driver_lname IS
    'The last name of the driver';

COMMENT ON COLUMN driver.driver_street IS
    'The street of the driver';

COMMENT ON COLUMN driver.driver_town IS
    'The town of the driver';

COMMENT ON COLUMN driver.driver_postcode IS
    'The postcode of the driver address';

COMMENT ON COLUMN driver.driver_dob IS
    'Date of birth of the driver';

COMMENT ON COLUMN driver.driver_licence_expiry_date IS
    'The driver''s licence expiry date';

COMMENT ON COLUMN driver.driver_demerit_point IS
    'Demerit points total accumulated by the driver';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_licence_no );

CREATE TABLE engine (
    eng_typ VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE engine
    ADD CONSTRAINT eng_typ CHECK ( eng_typ IN (
        'Diesel Engine',
        'Electrical Engine',
        'Gas',
        'Petrol Engine'
    ) );

COMMENT ON COLUMN engine.eng_typ IS
    'Type of engine. Can be more than one value.';

ALTER TABLE engine ADD CONSTRAINT engine_pk PRIMARY KEY ( eng_typ );

CREATE TABLE licence_type (
    driver_licence_no   NUMBER NOT NULL,
    vehicle_type_code   NUMBER NOT NULL
);

COMMENT ON COLUMN licence_type.driver_licence_no IS
    'licence number';

COMMENT ON COLUMN licence_type.vehicle_type_code IS
    'vehicle type code';

ALTER TABLE licence_type ADD CONSTRAINT licence_type_pk PRIMARY KEY ( driver_licence_no,
                                                                      vehicle_type_code );

CREATE TABLE manf_country (
    manf_country_isocode   VARCHAR2(5 CHAR) NOT NULL,
    manf_country_name      VARCHAR2(10 CHAR) NOT NULL
);

COMMENT ON COLUMN manf_country.manf_country_isocode IS
    'Manufacturer Country ISO code';

COMMENT ON COLUMN manf_country.manf_country_name IS
    'Manufacturer Country Name';

ALTER TABLE manf_country ADD CONSTRAINT manf_country_pk PRIMARY KEY ( manf_country_isocode );

CREATE TABLE manufacturer (
    manf_code   VARCHAR2(5 CHAR) NOT NULL,
    manf_name   VARCHAR2(10 CHAR) NOT NULL
);

COMMENT ON COLUMN manufacturer.manf_code IS
    'Manufacturer Code ';

COMMENT ON COLUMN manufacturer.manf_name IS
    'Name of Manufacturer';

ALTER TABLE manufacturer ADD CONSTRAINT manufacturer_pk PRIMARY KEY ( manf_code );

CREATE TABLE model (
    model_name                VARCHAR2(50 CHAR) NOT NULL,
    model_transmission_type   VARCHAR2(10 CHAR) NOT NULL,
    model_engine_size         VARCHAR2(5 CHAR) NOT NULL,
    model_laden_clearance     VARCHAR2(10 CHAR) NOT NULL,
    model_unladen_clearance   VARCHAR2(10 CHAR) NOT NULL,
    manf_code                 VARCHAR2(5 CHAR) NOT NULL,
    manf_country_isocode      VARCHAR2(5 CHAR) NOT NULL
);

ALTER TABLE model
    ADD CONSTRAINT tran_ty CHECK ( model_transmission_type IN (
        'automatic',
        'manual'
    ) );

COMMENT ON COLUMN model.model_name IS
    'Model Name of the model';

COMMENT ON COLUMN model.model_transmission_type IS
    'Transmission type of Model. One amongst Manual and Automatic';

COMMENT ON COLUMN model.model_engine_size IS
    'Engine size of the model in Litres';

COMMENT ON COLUMN model.model_laden_clearance IS
    'Laden clearance of the model in mm';

COMMENT ON COLUMN model.model_unladen_clearance IS
    'Unladen clearance of the model in mm';

COMMENT ON COLUMN model.manf_code IS
    'Manufacturer Code ';

COMMENT ON COLUMN model.manf_country_isocode IS
    'Manufacturer Country ISO code';

ALTER TABLE model ADD CONSTRAINT model_pk PRIMARY KEY ( model_name );

CREATE TABLE offence (
    offence_no          NUMBER NOT NULL,
    offence_location    VARCHAR2(30 CHAR) NOT NULL,
    offence_date        DATE NOT NULL,
    offence_time        VARCHAR2(10 CHAR) NOT NULL,
    demerit_code        VARCHAR2(10 CHAR) NOT NULL,
    officer_id          NUMBER NOT NULL,
    vin                 VARCHAR2(15 CHAR) NOT NULL,
    driver_licence_no   NUMBER NOT NULL
);

COMMENT ON COLUMN offence.offence_no IS
    'Unique offence number';

COMMENT ON COLUMN offence.offence_location IS
    'Location at which offence is recorded';

COMMENT ON COLUMN offence.offence_date IS
    'Date at which offence is recorded';

COMMENT ON COLUMN offence.offence_time IS
    'Time at which offence is recorded';

COMMENT ON COLUMN offence.demerit_code IS
    'Code of the demerit';

COMMENT ON COLUMN offence.officer_id IS
    'ID of the police officer';

COMMENT ON COLUMN offence.vin IS
    'vehicle identification number';

COMMENT ON COLUMN offence.driver_licence_no IS
    'licence number';

ALTER TABLE offence ADD CONSTRAINT offence_pk PRIMARY KEY ( offence_no );

CREATE TABLE police_allocation (
    allocation_start_date   DATE NOT NULL,
    officer_id              NUMBER NOT NULL,
    station_no              NUMBER NOT NULL
);

COMMENT ON COLUMN police_allocation.allocation_start_date IS
    'Start date of the allocation of a police officer to a police station';

COMMENT ON COLUMN police_allocation.officer_id IS
    'ID of the police officer';

COMMENT ON COLUMN police_allocation.station_no IS
    'Station number of a police station';

ALTER TABLE police_allocation
    ADD CONSTRAINT police_allocation_pk PRIMARY KEY ( allocation_start_date,
                                                      officer_id,
                                                      station_no );

CREATE TABLE police_officer (
    officer_id      NUMBER NOT NULL,
    officer_fname   VARCHAR2(10 CHAR) NOT NULL,
    officer_lname   VARCHAR2(10 CHAR) NOT NULL,
    officer_rank    VARCHAR2(15 CHAR) NOT NULL
);

COMMENT ON COLUMN police_officer.officer_id IS
    'ID of the police officer';

COMMENT ON COLUMN police_officer.officer_fname IS
    'First name of the police officer';

COMMENT ON COLUMN police_officer.officer_lname IS
    'Last name of the police officer';

COMMENT ON COLUMN police_officer.officer_rank IS
    'Rank of the police officer';

ALTER TABLE police_officer ADD CONSTRAINT police_officer_pk PRIMARY KEY ( officer_id );

CREATE TABLE police_station (
    station_no             NUMBER NOT NULL,
    station_add            VARCHAR2(30 CHAR) NOT NULL,
    station_phone_no       NUMBER NOT NULL,
    station_availability   VARCHAR2(6 CHAR) NOT NULL,
    officer_id             NUMBER NOT NULL
);

COMMENT ON COLUMN police_station.station_no IS
    'Station number of a police station';

COMMENT ON COLUMN police_station.station_add IS
    'Address of a police station';

COMMENT ON COLUMN police_station.station_phone_no IS
    'Phone number of the police station';

COMMENT ON COLUMN police_station.station_availability IS
    'The 24 hour availability of the police station. Will be either True or False';

COMMENT ON COLUMN police_station.officer_id IS
    'ID of the police officer';

ALTER TABLE police_station ADD CONSTRAINT police_station_pk PRIMARY KEY ( station_no );

CREATE TABLE registration (
    reg_date     DATE NOT NULL,
    reg_number   VARCHAR2(15 CHAR) NOT NULL,
    dereg_date   DATE,
    vin          VARCHAR2(15 CHAR) NOT NULL
);

COMMENT ON COLUMN registration.reg_date IS
    'the registration date of the vehicle';

COMMENT ON COLUMN registration.reg_number IS
    'the registration number for the vehicle';

COMMENT ON COLUMN registration.dereg_date IS
    'The de registration date of the vehicle';

COMMENT ON COLUMN registration.vin IS
    'the vehicle identification number';

ALTER TABLE registration ADD CONSTRAINT registration_pk PRIMARY KEY ( reg_date,
                                                                      vin );

CREATE TABLE suspension (
    driver_licence_no      NUMBER NOT NULL,
    suspension_startdate   DATE NOT NULL
);

COMMENT ON COLUMN suspension.driver_licence_no IS
    'driver licence number';

COMMENT ON COLUMN suspension.suspension_startdate IS
    'suspension start date';

ALTER TABLE suspension ADD CONSTRAINT suspension_pk PRIMARY KEY ( driver_licence_no,
                                                                  suspension_startdate );

CREATE TABLE suspension_date (
    suspension_startdate   DATE NOT NULL,
    suspension_enddate     DATE NOT NULL
);

COMMENT ON COLUMN suspension_date.suspension_startdate IS
    'The start  date of the suspension';

COMMENT ON COLUMN suspension_date.suspension_enddate IS
    'The end date of the suspension';

ALTER TABLE suspension_date ADD CONSTRAINT suspension_date_pk PRIMARY KEY ( suspension_startdate );

CREATE TABLE vehice (
    vin                 VARCHAR2(15 CHAR) NOT NULL,
    vehicle_manf_year   NUMBER NOT NULL,
    vehicle_color       VARCHAR2(10 CHAR) NOT NULL,
    model_name          VARCHAR2(50 CHAR) NOT NULL,
    vehicle_type_code   NUMBER NOT NULL
);

COMMENT ON COLUMN vehice.vin IS
    'THE VEHICLE IDENTIFICATION NUMBER';

COMMENT ON COLUMN vehice.vehicle_manf_year IS
    'the manufcature year of the vehicle';

COMMENT ON COLUMN vehice.vehicle_color IS
    'The vehicle colour';

COMMENT ON COLUMN vehice.model_name IS
    'model name';

COMMENT ON COLUMN vehice.vehicle_type_code IS
    'vehicle code';

ALTER TABLE vehice ADD CONSTRAINT vehice_pk PRIMARY KEY ( vin );

CREATE TABLE vehicle_type (
    vehicle_type_code   NUMBER NOT NULL,
    vehicle_type_name   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE vehicle_type
    ADD CONSTRAINT veh_typ CHECK ( vehicle_type_name IN (
        'car',
        'heavy combination truck',
        'heavy rigid truck',
        'light rigid truck',
        'marine',
        'medium combination truck',
        'medium rigid truck',
        'motorcycle',
        'tractor'
    ) );

COMMENT ON COLUMN vehicle_type.vehicle_type_code IS
    'the vehicle type''s code';

COMMENT ON COLUMN vehicle_type.vehicle_type_name IS
    'The vehicle type name';

ALTER TABLE vehicle_type ADD CONSTRAINT vehicle_type_pk PRIMARY KEY ( vehicle_type_code );

ALTER TABLE cancellation
    ADD CONSTRAINT cancellation_cancelduration FOREIGN KEY ( cancel_reason )
        REFERENCES cancel_duration ( cancel_reason );

ALTER TABLE offence
    ADD CONSTRAINT demerit_offence FOREIGN KEY ( demerit_code )
        REFERENCES demerit ( demerit_code );

ALTER TABLE cancellation
    ADD CONSTRAINT driver_cancellation FOREIGN KEY ( driver_licence_no )
        REFERENCES driver ( driver_licence_no );

ALTER TABLE licence_type
    ADD CONSTRAINT driver_licencetype FOREIGN KEY ( driver_licence_no )
        REFERENCES driver ( driver_licence_no );

ALTER TABLE offence
    ADD CONSTRAINT driver_offence FOREIGN KEY ( driver_licence_no )
        REFERENCES driver ( driver_licence_no );

ALTER TABLE suspension
    ADD CONSTRAINT driver_suspension FOREIGN KEY ( driver_licence_no )
        REFERENCES driver ( driver_licence_no );

ALTER TABLE accommodate
    ADD CONSTRAINT engine_accomodation FOREIGN KEY ( eng_typ )
        REFERENCES engine ( eng_typ );

ALTER TABLE model
    ADD CONSTRAINT manf_country_model FOREIGN KEY ( manf_country_isocode )
        REFERENCES manf_country ( manf_country_isocode );

ALTER TABLE model
    ADD CONSTRAINT manufacturer_model FOREIGN KEY ( manf_code )
        REFERENCES manufacturer ( manf_code );

ALTER TABLE accommodate
    ADD CONSTRAINT model_accomodate FOREIGN KEY ( model_name )
        REFERENCES model ( model_name );

ALTER TABLE vehice
    ADD CONSTRAINT model_vehicle FOREIGN KEY ( model_name )
        REFERENCES model ( model_name );

ALTER TABLE police_allocation
    ADD CONSTRAINT police_officer_allocation FOREIGN KEY ( officer_id )
        REFERENCES police_officer ( officer_id );

ALTER TABLE offence
    ADD CONSTRAINT police_officer_offence FOREIGN KEY ( officer_id )
        REFERENCES police_officer ( officer_id );

ALTER TABLE police_station
    ADD CONSTRAINT police_officer_station FOREIGN KEY ( officer_id )
        REFERENCES police_officer ( officer_id );

ALTER TABLE police_allocation
    ADD CONSTRAINT police_station_allocation FOREIGN KEY ( station_no )
        REFERENCES police_station ( station_no );

ALTER TABLE suspension
    ADD CONSTRAINT suspensiondate_suspension FOREIGN KEY ( suspension_startdate )
        REFERENCES suspension_date ( suspension_startdate );

ALTER TABLE offence
    ADD CONSTRAINT vehicle_offence FOREIGN KEY ( vin )
        REFERENCES vehice ( vin );

ALTER TABLE registration
    ADD CONSTRAINT vehicle_registration FOREIGN KEY ( vin )
        REFERENCES vehice ( vin );

ALTER TABLE licence_type
    ADD CONSTRAINT vehicletype_licence FOREIGN KEY ( vehicle_type_code )
        REFERENCES vehicle_type ( vehicle_type_code );

ALTER TABLE vehice
    ADD CONSTRAINT vehicletype_vehicle FOREIGN KEY ( vehicle_type_code )
        REFERENCES vehicle_type ( vehicle_type_code );

SPOOL OFF;
SET ECHO OFF

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             0
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
